---
deployment:
  tasks:
    - /bin/mkdir -p /home3/portopsy/public_html/qs
    - /usr/bin/rsync -av --exclude='.git' /home3/portopsy/home/cpses_po229tqt4f/public_html/qs/ /home3/portopsy/public_html/qs/
